# Generated by Django 4.2 on 2023-05-08 22:28

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="cpf",
            field=cpf_field.models.CPFField(max_length=14, unique=True),
        ),
    ]
