# Generated by Django 4.2 on 2023-05-31 10:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_customer_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="cpf",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="instagram",
        ),
    ]
