# Generated by Django 4.2 on 2023-05-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="contract",
            field=models.FileField(blank=True, null=True, upload_to="contracts/"),
        ),
        migrations.AddField(
            model_name="house",
            name="late_payment",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="house",
            name="vacant",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="building",
            name="concierge",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="building",
            name="elevator",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="house",
            name="backyard",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="house",
            name="garage",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="house",
            name="pool",
            field=models.BooleanField(default=False),
        ),
    ]
