# Generated by Django 4.2 on 2023-05-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0002_house_contract_house_late_payment_house_vacant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="floor",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
