# Generated by Django 4.2 on 2023-05-07 13:18

import cpf_field.models
from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="cnpj",
            field=cpf_field.models.CPFField(
                blank=True, max_length=14, null=True, unique=True, verbose_name="cnpj"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="cpf",
            field=cpf_field.models.CPFField(
                blank=True, max_length=14, null=True, unique=True, verbose_name="cpf"
            ),
        ),
    ]
